// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFs1Qg4-N4tpswxum2hZf5yQM41DTloLA',
    appId: '1:782758238451:web:df2cdbd89b20809036bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    authDomain: 'smart-accident-system.firebaseapp.com',
    storageBucket: 'smart-accident-system.appspot.com',
    measurementId: 'G-B656XG9VP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevzjss4WUBVoBo3oiivM9avt27pjJcbk',
    appId: '1:782758238451:android:7baedf8abf78f64936bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    storageBucket: 'smart-accident-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF7LvVAro1UwcSshVsle67FjlqyMXkZ4A',
    appId: '1:782758238451:ios:00f451a6e84d128a36bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    storageBucket: 'smart-accident-system.appspot.com',
    iosBundleId: 'com.example.userAccident',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF7LvVAro1UwcSshVsle67FjlqyMXkZ4A',
    appId: '1:782758238451:ios:00f451a6e84d128a36bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    storageBucket: 'smart-accident-system.appspot.com',
    iosBundleId: 'com.example.userAccident',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFs1Qg4-N4tpswxum2hZf5yQM41DTloLA',
    appId: '1:782758238451:web:636179fe408bc12036bf86',
    messagingSenderId: '782758238451',
    projectId: 'smart-accident-system',
    authDomain: 'smart-accident-system.firebaseapp.com',
    storageBucket: 'smart-accident-system.appspot.com',
    measurementId: 'G-8KXD8YJR18',
  );
}
